In [1]:
import numpy as np
import pandas as pd

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding
from keras.layers import GRU
from keras.layers import SimpleRNN
from keras.callbacks import EarlyStopping

from keras.datasets import imdb

In [2]:
n_words = 1000
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=n_words)
print('Train seq: {}'.format(len(X_train)))
print('Test seq: {}'.format(len(X_train)))

Train seq: 25000
Test seq: 25000


In [3]:
# Pad sequences with max_len
max_len = 200
X_train = sequence.pad_sequences(X_train, maxlen=max_len)
X_test = sequence.pad_sequences(X_test, maxlen=max_len)

In [4]:
# Define network architecture and compile
model = Sequential()
model.add(Embedding(n_words, 50, input_length=max_len))
model.add(Dropout(0.2))

model.add(GRU(100, dropout=0.2, recurrent_dropout=0.2))
#use simple RNN instead of GRU

# model.add(SimpleRNN(50, dropout=0.2, recurrent_dropout=0.2))
# model.add(Dense(250, activation='relu'))
# model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',  optimizer='adam', metrics=['accuracy'])
model.summary()

2022-05-06 10:12:58.041902: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-05-06 10:12:58.123360: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2022-05-06 10:12:58.134044: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2022-05-06 10:12:58.134066: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the req

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 200, 50)           50000     
                                                                 
 dropout (Dropout)           (None, 200, 50)           0         
                                                                 
 gru (GRU)                   (None, 100)               45600     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 95,701
Trainable params: 95,701
Non-trainable params: 0
_________________________________________________________________


In [5]:
callbacks = [EarlyStopping(monitor='val_accuracy', patience=2)]

In [6]:
batch_size = 512
n_epochs = 100

model.fit(X_train, y_train, batch_size=batch_size, epochs=n_epochs, validation_split=0.2, callbacks=callbacks)

Epoch 1/100
40/40 [==============================] - 33s 761ms/step - loss: 0.6750 - accuracy: 0.5660 - val_loss: 0.5750 - val_accuracy: 0.7086
Epoch 2/100
40/40 [==============================] - 31s 772ms/step - loss: 0.4640 - accuracy: 0.7839 - val_loss: 0.4066 - val_accuracy: 0.8134
Epoch 3/100
40/40 [==============================] - 30s 763ms/step - loss: 0.3649 - accuracy: 0.8392 - val_loss: 0.3580 - val_accuracy: 0.8430
Epoch 4/100
40/40 [==============================] - 29s 717ms/step - loss: 0.3576 - accuracy: 0.8454 - val_loss: 0.3768 - val_accuracy: 0.8368
Epoch 5/100
40/40 [==============================] - 28s 710ms/step - loss: 0.3349 - accuracy: 0.8572 - val_loss: 0.3859 - val_accuracy: 0.8426


In [7]:
print('Accuracy on test set: {}'.format(model.evaluate(X_test, y_test)[1]))

782/782 [==============================] - 18s 23ms/step - loss: 0.3719 - accuracy: 0.8452
Accuracy on test set: 0.8452399969100952


In [8]:
print(X_test)

[[  0   0   0 ...  14   6 717]
 [  2   2  45 ... 125   4   2]
 [  2 189   4 ...   9  57 975]
 ...
 [  0   0   0 ...  21 846   2]
 [  0   0   0 ...   2   7 470]
 [  0   0   0 ...  34   2   2]]


In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 200, 50)           50000     
                                                                 
 dropout (Dropout)           (None, 200, 50)           0         
                                                                 
 gru (GRU)                   (None, 100)               45600     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 95,701
Trainable params: 95,701
Non-trainable params: 0
_________________________________________________________________
