In [1]:
import numpy as np
import pandas as pd

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding
from keras.layers import GRU
from keras.layers import SimpleRNN
from keras.callbacks import EarlyStopping

from keras.datasets import imdb

In [2]:
n_words = 1000
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=n_words)
print('Train seq: {}'.format(len(X_train)))
print('Test seq: {}'.format(len(X_train)))

Train seq: 25000
Test seq: 25000


In [3]:
# Pad sequences with max_len
max_len = 200
X_train = sequence.pad_sequences(X_train, maxlen=max_len)
X_test = sequence.pad_sequences(X_test, maxlen=max_len)

In [4]:
# Define network architecture and compile
model = Sequential()
model.add(Embedding(n_words, 50, input_length=max_len))
model.add(Dropout(0.2))

#model.add(GRU(100, dropout=0.2, recurrent_dropout=0.2))
#use simple RNN instead of GRU

model.add(SimpleRNN(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(250, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',  optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 200, 50)           50000     
_________________________________________________________________
dropout (Dropout)            (None, 200, 50)           0         
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 100)               15100     
_________________________________________________________________
dense (Dense)                (None, 250)               25250     
_________________________________________________________________
dropout_1 (Dropout)          (None, 250)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 251       
Total params: 90,601
Trainable params: 90,601
Non-trainable params: 0
____________________________________________________

In [5]:
callbacks = [EarlyStopping(monitor='val_accuracy', patience=2)]

In [6]:
batch_size = 512
n_epochs = 100

model.fit(X_train, y_train, batch_size=batch_size, epochs=n_epochs, validation_split=0.2, callbacks=callbacks)

Epoch 1/100
40/40 [==============================] - 25s 366ms/step - loss: 0.6986 - accuracy: 0.4988 - val_loss: 0.6925 - val_accuracy: 0.5116
Epoch 2/100
40/40 [==============================] - 13s 331ms/step - loss: 0.6976 - accuracy: 0.5024 - val_loss: 0.6934 - val_accuracy: 0.5090
Epoch 3/100
40/40 [==============================] - 13s 334ms/step - loss: 0.6962 - accuracy: 0.5067 - val_loss: 0.6913 - val_accuracy: 0.5266
Epoch 4/100
40/40 [==============================] - 13s 331ms/step - loss: 0.6963 - accuracy: 0.5098 - val_loss: 0.6947 - val_accuracy: 0.4934
Epoch 5/100
40/40 [==============================] - 15s 371ms/step - loss: 0.6933 - accuracy: 0.5196 - val_loss: 0.7027 - val_accuracy: 0.4938


In [7]:
print('Accuracy on test set: {}'.format(model.evaluate(X_test, y_test)[1]))

782/782 [==============================] - 18s 23ms/step - loss: 0.7005 - accuracy: 0.5000
Accuracy on test set: 0.5


In [8]:
print(X_test)

[[  0   0   0 ...  14   6 717]
 [  2   2  45 ... 125   4   2]
 [  2 189   4 ...   9  57 975]
 ...
 [  0   0   0 ...  21 846   2]
 [  0   0   0 ...   2   7 470]
 [  0   0   0 ...  34   2   2]]
